/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.java.com.peluqueria.ui;

/**
 *
 * @author LAB-USR-LCENTRO
 */
public class Navbar extends javax.swing.JPanel {

    /**
     * Creates new form Navbar
     */
    public Navbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavBar = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        NavBar.setBackground(new java.awt.Color(255, 255, 255));
        NavBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, null, java.awt.Color.lightGray));
        NavBar.setPreferredSize(new java.awt.Dimension(1700, 80));
        NavBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Logo.png"))); // NOI18N
        NavBar.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 68, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(255, 204, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 99, 71));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Cerrar sesion.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setActionCommand("Citas");
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        NavBar.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 20, 160, 50));

        btnDashboard.setBackground(new java.awt.Color(255, 228, 225));
        btnDashboard.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 99, 71));
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Home.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NavBar.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 160, 50));

        btnCitas.setBackground(new java.awt.Color(255, 228, 225));
        btnCitas.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnCitas.setForeground(new java.awt.Color(255, 99, 71));
        btnCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Citas.png"))); // NOI18N
        btnCitas.setText("Citas");
        btnCitas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });
        NavBar.add(btnCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 130, 50));

        btnClientes.setBackground(new java.awt.Color(255, 228, 225));
        btnClientes.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 99, 71));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Clientes.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setActionCommand("Citas");
        btnClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        NavBar.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 130, 50));

        btnInventario.setBackground(new java.awt.Color(255, 228, 225));
        btnInventario.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 99, 71));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Inventario.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setActionCommand("Citas");
        btnInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        NavBar.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 170, 50));

        btnVentas.setBackground(new java.awt.Color(255, 228, 225));
        btnVentas.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 99, 71));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Ventas.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setActionCommand("Citas");
        btnVentas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        NavBar.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 140, 50));

        btnReportes.setBackground(new java.awt.Color(255, 228, 225));
        btnReportes.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 99, 71));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Reporte.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setActionCommand("Citas");
        btnReportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        NavBar.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCitasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel NavBar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVentas;
    // End of variables declaration//GEN-END:variables
}
